; vim: set et ts=8 sts=8 sw=8 fdm=marker syntax=64tass:
;
; BDP 6 - KERNAL calls header

K_SCINIT = $ff81
K_IOINIT = $ff84
K_RAMTAS = $ff87
K_RESTOR = $ff8a
K_VECTOR = $ff8d
K_SETMSG = $ff90
K_LSTNSA = $ff93
K_TALKSA = $ff96
K_MEMBOT = $ff99
K_MEMTOP = $ff9c
K_SCNKEY = $ff9f
K_SETTMO = $ffa2
K_IECIN  = $ffa5
K_IECOUT = $ffa8
K_UNTALK = $ffab
K_UNLSTN = $ffae
K_LISTEN = $ffb1
K_TALK   = $ffb4
K_READST = $ffb7
K_SETLFS = $ffba
K_SETNAM = $ffbd
K_OPEN   = $ffc0
K_CLOSE  = $ffc3
K_CHKIN  = $ffc6
K_CHKOUT = $ffc9
K_CLRCHN = $ffcc
K_CHRIN  = $ffcf
K_CHROUT = $ffd2
K_LOAD   = $ffd5
K_SAVE   = $ffd8
K_SETTIM = $ffdb
K_RDTIM  = $ffde
K_STOP   = $ffe1
K_GETIN  = $ffe4
K_CLALL  = $ffe7
K_UDTIM  = $ffea
K_SCREEN = $ffed
K_PLOT   = $fff0
K_IOBASE = $fff3

